import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';

export type Channel = 'instagram' | 'tiktok' | 'youtube';

export interface MetricRow {
  snapshot_date: string;
  reach: number | null;
  impressions: number | null;
  engagement: number | null;
  likes: number | null;
  comments: number | null;
  saves: number | null;
  shares: number | null;
  video_views: number | null;
  video_completion_rate: number | null;
  avg_view_sec: number | null;
  watch_minutes: number | null;
  followers_total: number | null;
  new_followers: number | null;
  caption_excerpt: string | null;
  external_post_id: string;
  is_account_level: boolean;
}

export interface PerformanceQuery {
  brandId: string | null;
  channel: Channel;
  from: string;        // YYYY-MM-DD
  to: string;          // YYYY-MM-DD inclusive
}

export interface PerformanceResult {
  rows: MetricRow[];
  prevRows: MetricRow[];
  loading: boolean;
  error: string | null;
}

/**
 * Pulls daily-snapshot rows for (brand, channel, period) and ALSO the
 * preceding window of equal length — so the caller can compute deltas %.
 * RLS handles authorization: admins get cross-brand reads automatically.
 */
export const usePerformanceMetrics = ({ brandId, channel, from, to }: PerformanceQuery): PerformanceResult => {
  const [state, setState] = useState<PerformanceResult>({
    rows: [], prevRows: [], loading: false, error: null,
  });

  useEffect(() => {
    if (!brandId) {
      setState({ rows: [], prevRows: [], loading: false, error: null });
      return;
    }
    let cancelled = false;
    setState((s) => ({ ...s, loading: true, error: null }));

    (async () => {
      // current window — cast to any: types.ts autogenerated doesn't yet
      // include post_metrics (added in 20260618121000 migration).
      const cur: any = await (supabase as any)
        .from('post_metrics')
        .select('*')
        .eq('brand_id', brandId)
        .eq('channel', channel)
        .gte('snapshot_date', from)
        .lte('snapshot_date', to)
        .order('snapshot_date', { ascending: true });

      if (cur.error) {
        if (cancelled) return;
        setState({ rows: [], prevRows: [], loading: false, error: cur.error.message });
        return;
      }

      // previous window of equal length (for delta %)
      const periodDays = Math.max(1, Math.round(
        (Date.parse(to) - Date.parse(from)) / 86_400_000
      ) + 1);
      const prevFrom = new Date(Date.parse(from) - periodDays * 86_400_000)
        .toISOString().slice(0, 10);
      const prevTo = new Date(Date.parse(from) - 86_400_000)
        .toISOString().slice(0, 10);

      const prev: any = await (supabase as any)
        .from('post_metrics')
        .select('*')
        .eq('brand_id', brandId)
        .eq('channel', channel)
        .gte('snapshot_date', prevFrom)
        .lte('snapshot_date', prevTo);

      if (cancelled) return;
      if (prev.error) {
        setState({ rows: (cur.data || []) as MetricRow[], prevRows: [], loading: false, error: prev.error.message });
        return;
      }
      setState({
        rows: (cur.data || []) as MetricRow[],
        prevRows: (prev.data || []) as MetricRow[],
        loading: false,
        error: null,
      });
    })();

    return () => { cancelled = true; };
  }, [brandId, channel, from, to]);

  return state;
};
