// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdufnmakqssyycbblmut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdWZubWFrcXNzeXljYmJsbXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjI3MzMsImV4cCI6MjA2NTYzODczM30.bN0dAjVmOi05Nybd17p7iK0BIVnenYDEeowCeNhOXhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'fisioaccordo-auth',
  }
});